site_name: MAGIC Documentation
theme:
  name: material
  features:
    - navigation.sections
    - toc.integrate 
    - content.code.annotate
    - navigation.tabs
    - toc.follow
  palette:
    scheme: slate
    primary: purple
    accent: light green
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: fontawesome/solid/wand-magic-sparkles
    
markdown_extensions:
  - attr_list
  - toc:
      toc_depth: 2  # Only show H1&2 in TOC
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details