project:
  name: magic_chess_board
  version: "0.0.0"
  description: "MAGIC CHESS FYP"

models:
  chess_board:
    size_x: 40.0
    size_y: 40.0
    square_size: 5.0
  
  graveyard:
    size_x: 10
    size_y: 40

gantry:
  quick_speed: 15
  slow_speed: 10

game:
  archived_mode: false  # Set to true if play showing old game with API
  archived_moves: []    # List of moves from the old game